### ISSUE TITLE
ant-deploy not loading xercesImpl library correctly

### ISSUE THREAD

**Issue by brendon-stephens** [SysIntAu/DPDirectServicesFramework#13]
The ant-deploy task references the xercesImpl library for use in the DPDirectTask class.

`	<path id="dpdirect.class.path">
		<pathelement location="${dpdirect.dir}/dpdirect-1.0.5.jar"/>
		<pathelement location="${dpdirect.dir}/lib/xercesImpl.jar"/>
		<pathelement location="${dpdirect.dir}/lib/log4j.jar"/>
		<pathelement location="${dpdirect.dir}/lib/xml-apis.jar"/>
	</path>`

When running the deploy.bat file - I get a class not found error:

` [dpDeploy] 2019-09-07 20:37:45,065 ERROR org.dpdirect.dpmgmt.DPDirectBase - org.apache.xerces.dom.DOMXSImplementationSourceImpl
 [dpDeploy] java.lang.ClassNotFoundException: org.apache.xerces.dom.DOMXSImplementationSourceImpl
 [dpDeploy]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 [dpDeploy]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 [dpDeploy]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 [dpDeploy]     at org.w3c.dom.bootstrap.DOMImplementationRegistry.newInstance(DOMImplementationRegistry.java:182)
 [dpDeploy]     at org.dpdirect.schema.SchemaLoader.<init>(SchemaLoader.java:139)
...`

It appears that the library is not correctly loading into the class path. 

I am able to fix the problem by manually copying the xercesImpl.jar file into my %ANT_HOME%/lib folder. 

Any ideas?

**Comment by goodwillta** [comment]
Noe: There is currently an ant-task xerces issue running under any ant version above 1.8.0.
Until the issue is resolved, Please copy dpdirect/lib/xercesImpl.jar into your ant-[version]/lib folder. 
Or, alternatively, run the ant-task with the ant 1.8.0 distribution.
